/*
	Erick Octavio Nolasco Machuca
	NoControl:17401029
	Practica:18
	Fecha:18 de mayo de 2020
*/
/*RESTAURA EL RESPALDO COMPLETO 1 DE LA BD PUBS EN OTRA
UBICACIÓN Y CON UN NOMBRE NUEVO DE LA BD
(PUBLICACIONES) TANTO FISICO COMO LOGICO*/

RESTORE FILELISTONLY
FROM DISK='C:\BD\unidad 4\Respaldos\RESPUBS1.BAK';

RESTORE DATABASE PUBLICACIONES
FROM DISK ='C:\BD\unidad 4\Respaldos\RESPUBS1.BAK'
WITH MOVE 'pubs'
TO 'C:\BD\unidad 4\Respaldos\Disco3\PUBLICACIONES.MDF'
,
MOVE 'pubs_log'
TO 'C:\BD\unidad 4\Respaldos\Disco3\PUBLICACIONES.LDF'

GO