/*Erick Octavio Nolasco Machuca
	Practica:26
	NoControl:17401029
	Fecha: 20 de mayo de 2020
*/

/*
PRACTICA 26. BCP – IN
TESTER_NORTWIND
EL ARCHIVO QUE GE-NERASTE PARA LA TABLA MIGRACION USALO Y
MODIFICALO PARA CONFIGURARLO QUE TENGAN EL FORMATO O
ESTRUCTURA DE LA TABLA DE EMPLEADOS. IMPORTARLOS CON BCP
*/

/*BCP INTRODUCIDO
BCP TESTER_NORTWIND.dbo.Employees in "C:\BD\unidad 4\P26IN.txt" -c -t, -r\n -T

*/
