/*
	Erick Octavio Nolasco Machuca
	Fecha: 3 de mayo de 2020
	Practica: 3

	Instrucciones:
	PRACTICA 3.
RETOMA LA BD DE DATOS ALMACEN DE LA UNIDAD DOS,
NOLA PARTICIONES. CREALE UN RESPALDO COMPLETO CON
AL MENOS 4 PARAMETROS UTILIZA DISTINTOS A LOS QUE
HAZ USADO HASTA AHORITA.
*/

BACKUP DATABASE ALMACEN
TO DISK = 'C:\BD\unidad 4\Respaldos\RESALMACEN1.BAK'
WITH NOINIT,
NAME = 'MI RESPALDO DE Almacen 1',
DESCRIPTION = 'RESPALDO COMPLETO 03-05-2020, estado original',
EXPIREDATE = '2020/06/05',
STATS = 10,
NO_COMPRESSION;