/*
	Erick Octavio Nolasco Machuca
	Practica: 16
	Fecha: 18 de mayo de 2020

*/

/*PRACTICA 16
RESTAURA EL PRIMER RESPALDO COMPLETO DE NORTHWIND, EN
OTRA UBICACIÓN Y CON OTRO NOMBRE EL NOMBRE DEBE SER :
TESTER_NORTWIND, LA UBICACIÓN NUEVA TU LA ELIGES*/
RESTORE FILELISTONLY
FROM DISK='C:\BD\unidad 4\Respaldos\COMP1_NORTH.BAK';

RESTORE DATABASE TESTER_NORTWIND
FROM DISK ='C:\BD\unidad 4\Respaldos\COMP1_NORTH.BAK'
WITH MOVE 'Northwind'
TO 'C:\BD\unidad 4\Respaldos\Disco3\TESTER_NORTWIND.MDF'
,
MOVE 'Northwind_log'
TO 'C:\BD\unidad 4\Respaldos\Disco3\TESTER_NORTWIND.LDF'
go