-- CREA DE NUEVO LA BD DE DATOS NORHTWIND Y
-- CREALE UN RESPALDO COMPLETO ANTES DE HACER
-- CUALQUIER MODIFICACION
-- CON LOS SIGUIENES PARAMETROS : NOMBRE,
-- DESCRIPCION Y QUE MUESTRE EL AVANCE DE
-- DE 10% EN 10%

BACKUP DATABASE NORTHWIND
TO DISK =
'C:\BD\unidad 4\Respaldos\COMP1_NORTH.BAK'
WITH
NAME = 'MI RESPALDO COMPRIMIDO DE NORTHWIND',
DESCRIPTION = 'RESPALDO COMPLETO 21-04-2020',
STATS = 10
GO